[theme]
# Primary accent color for interactive elements.
primaryColor = "#74BEE0"

# Background color for the main content area.
backgroundColor = "#EBE7E4"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "37207D"

# Color used for almost all text.
textColor = "#121110"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
